{{- if eq .Values.releaseType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}'
  labels:
    app: fattariello-db-server
spec:
  selector:
    matchLabels:
      app: fattariello-db-server
  replicas: {{.Values.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fattariello-db-server
    spec:
      volumes:
        - name: fattariello-db-server-pvc
          persistentVolumeClaim:
            claimName: '{{.Release.Name}}-fattariello-db-server-pvc'
      containers:
        - name: fattariellodb-server
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_ADDRESS
              value: "{{ .Values.envValues.serverAddress }}"
          command: ["/fattarielloServer"]
          args: ["$(SERVER_ADDRESS)"]
          ports:
            - name: grpc
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          volumeMounts:
            - name: fattariello-db-server-pvc
              mountPath: /mnt
              subPath: db/
          #securityContext:
          #  runAsGroup: 999
          #  runAsNonRoot: true
      serviceAccountName: fattariello-db-server-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
{{- end }}