apiVersion: v1
kind: PersistentVolume
metadata:
  name: fattariello-db-server-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db"