apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-fattariello-db-server-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi