apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fattariello-db-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: fattariello-db-server
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 8888
      targetPort: {{ .Values.serverPort }}
  selector:
    app: fattariello-db-server